version: '3.8'
name: moovy

services:
  moovy_db:
    image: postgres:15-alpine
    container_name: moovy-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moovy_db
    volumes:
      - moovy_data:/var/lib/postgresql/data

volumes:
  moovy_data:
