version: '3.8'

services:
  moovy_db:
    image: postgis/postgis:15-3.3-alpine
    container_name: moovy-db
    ports:
      - "5436:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moovy_db
    volumes:
      - moovy_data:/var/lib/postgresql/data

volumes:
  moovy_data:
